### ISSUE TITLE
USER STORY: Sign up for an account

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#1]
As a **user** I can **sign up for an account** so that **I can create a profile**

### Acceptance Criteria:
* Acceptance Criteria 1: A sign up button link should be visible to non logged in users on the site nav bar and footer
* Acceptance Criteria 2: Clicking the sign up button should direct the user to the sign up form page
* Acceptance Criteria 3: Successful sign up form submission should direct the user to the sign in page 

### Tasks:
- [x] Add sign up button link to the nav bar and footer menus
- [x] Add conditional to button to only display if the user is logged out
- [x] Add URL link to button to navigate to the dj rest auth sign up url
- [x] Add sign up form component with on change and on submit methods
- [x] Add route for sign up form to app.js
- [x] Add redirect to sign in page on successful submission
- [x] Test functionality
