### ISSUE TITLE
USER STORY: Comment on rigs

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#10]
As a **user** I can **comment on rigs** so that **I can engage with the community and the author**

### Acceptance Criteria:
* Acceptance Criteria 1: A list of comments from users should be visible on the rig pages
* Acceptance Criteria 2: A comment form should be visible to logged in users so they can post a comment
* Acceptance Criteria 3: Clicking the comment form submit button should add the comment at the top of the rig page comment list 

### Tasks:
- [x] Add comment section to rig page
- [x] Add loop to display comments on page in descending updated on order
- [x] Add comment form 
- [x] Add conditional to comment form to display only to logged in users
- [x] Add comment form on change and on submit methods
- [x] Test functionality
