### ISSUE TITLE
USER STORY: Edit comments

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#11]
As a **user** I can **edit my comments** so that **I can change and update the comment**

### Acceptance Criteria:
* Acceptance Criteria 1: A menu button icon should be visible on any comments made by a user 
* Acceptance Criteria 2: Clicking the menu button should open a dropdown menu with an edit button 
* Acceptance Criteria 3: Clicking the edit button should open the edit comment form component
* Acceptance Criteria 4: The form fields should be pre filled out with the content of the comment
* Acceptance Criteria 5: If a user edits the form field and clicks the submit button the comment should be returned back into view with the edited content visible
* Acceptance Criteria 6: If a user clicks the cancel button the form should be closed and the unedited comment returned to view

### Tasks:
- [x] Import and add dropdown component into comment component
- [x] Add conditional to only be visible if user is logged in and owns the comment
- [x] Add edit comment form component with on submit and on change methods
- [x] Test functionality
