### ISSUE TITLE
USER STORY: Delete comments

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#12]
As a **user** I can **delete my comments** so that **I can remove my comment from the rig comment section**

### Acceptance Criteria:
* Acceptance Criteria 1: A delete button should be visible in the comment dropdown menu to logged in users that own the comment
* Acceptance Criteria 2: When clicked, the comment should be deleted and the comment list should be re-rendered displaying the new list without the comment 

### Tasks:
- [x] Add delete button to comment dropdown menu
- [x] Add conditional for comment dropdown menu
- [x] Add handle delete function to comment component
- [x] Test functionality
