### ISSUE TITLE
USER STORY: Like a rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#13]
As a **user** I can **like another users rig** so that **I can show my appreciation to the author and increase the rigs visibility to other users**

### Acceptance Criteria:
* Acceptance Criteria 1: A like button should be visible on each rig card and rig page 
* Acceptance Criteria 2: The like button should only be visible if the user is logged in and doesn't own the rig
* Acceptance Criteria 3: Clicking the like button should add one like to the rig like count and remove the like button from view

### Tasks:
- [x] Add like button to rig card and rig page
- [x] Add like method 
- [x] Add conditional to only display if user is logged in and doesn't own the rig
- [x] Test functionality
