### ISSUE TITLE
USER STORY: Unlike a rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#14]
As a **user** I can **unlike a rig** so that **I can lower a rigs visibility among other users**

### Acceptance Criteria:
* Acceptance Criteria 1: An unlike button should be visible on each rig card and rig page 
* Acceptance Criteria 2: The unlike button should only be visible if the user is logged in, doesn't own the rig and has liked the rig previously
* Acceptance Criteria 3: Clicking the unlike button should minus one like from the rig like count, remove the unlike button from view and return the like button to view

### Tasks:
- [x] Add unlike button to rig card and rig page
- [x] Add unlike method 
- [x] Add conditional to only display if user is logged in, doesn't own the rig and has previously liked the rig
- [x] Test functionality
