### ISSUE TITLE
USER STORY: Edit gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#18]
As a **user** I can **edit gear items** so that **I can change and update item details**

### Acceptance Criteria:
* Acceptance Criteria 1: A dropdown menu with an edit icon button should be visible to users on their gear cards
* Acceptance Criteria 2: Clicking the edit icon button should redirect the user to the gear edit form 
* Acceptance Criteria 3: The form should be autofilled with the data from the instance of gear the user wishes to edit
* Acceptance Criteria 4: Any fields that are updated should be reflected in the updated gear card when the user clicks the save button on the form
* Acceptance Criteria 5: Form submission should redirect the user back to the gear page

### Tasks:
- [x] Add edit icon button to the gear dropdown menu with a link to the edit gear page
- [x] Add route for the edit gear form into app.js
- [x] Create edit gear form component with handle submit and handle change functions
- [x] Test functionality
