### ISSUE TITLE
USER STORY: Delete gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#19]
As a **user** I can **delete gear items** so that **I can remove it from my gear list**

### Acceptance Criteria:
* Acceptance Criteria 1: A dropdown menu should be visible to users on their gear cards
* Acceptance Criteria 2: Clicking the delete button on the dropdown menu should delete the gear item
* Acceptance Criteria 3: Upon deletion the gear list should re-render to display the new list without the deleted item

### Tasks:
- [x] Add dropdown menu component with click outside function
- [x] Import dropdown menu component into gear card component
- [x] Add handle delete function into gear card and pass as prop to dropdown menu component
- [x] Test functionality
