### ISSUE TITLE
USER STORY: Log into account

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#2]
As a **user** I can **log into my account** so that **I can access all the site features**

### Acceptance Criteria:
* Acceptance Criteria 1: A log in page link should be visible on the nav bar and in the footer to non logged in users 
* Acceptance Criteria 2: Clicking the link should direct the user to the log in form page
* Acceptance Criteria 3: Filling in the form correctly should direct the user to the homepage and display their profile link in the navbar as well as the other pages only available to logged in users

### Tasks:
- [ ] Add log in page component
- [ ] Add on change and on submit methods for log in form
- [ ] Add route for log in page component to app.js
- [ ] Add redirect to homepage on successful log in
- [ ] Test functionality
