### ISSUE TITLE
USER STORY: Add category to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#20]
As a **user** I can **add a category to my gear items** so that **I they can be automatically organised on my profile**

### Acceptance Criteria:
* Acceptance Criteria 1: A category field should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: The category field should be a select field with multiple options
* Acceptance Criteria 3: Upon submission, the category field data should be visible on the gear card 

### Tasks:
- [x] Add category field to gear model with category options
- [x] Migrate database
- [x] Add category select field to gear create and edit forms
- [x] Add category field data into use state and handle submit function
- [x] Test functionality
