### ISSUE TITLE
USER STORY: Add brand and model to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#21]
As a **user** I can **add a brand and model to my gear items** so that **I can see them displayed on my gear page**

### Acceptance Criteria:
* Acceptance Criteria 1: Brand and model fields should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the brand and model field data should be visible on the gear card

### Tasks:
- [x] Add brand and model fields to gear model
- [x] Migrate database
- [x] Add brand and model fields to gear create and edit forms
- [x] Add brand and model field data into use state and handle submit function
- [x] Test functionality
