### ISSUE TITLE
USER STORY: Add value amount to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#22]
As a **user** I can **add a value to my gear items** so that **I can see a total value of my gear displayed on my gear page**

### Acceptance Criteria:
* Acceptance Criteria 1: A value field should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the value field data should be visible on the users gear card 

### Tasks:
- [x] Add value field to gear model
- [x] Migrate database
- [x] Add value field to gear create and edit forms
- [x] Add value field data into use state and handle submit function
- [x] Test functionality
