### ISSUE TITLE
USER STORY: Add image to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#23]
As a **user** I can **add an image to my gear items** so that **my gear is displayed with images on my gear page**

### Acceptance Criteria:
* Acceptance Criteria 1: An image input field should appear on the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the image should be visible on the gear card 

### Tasks:
- [x] Add image field to gear model
- [x] Migrate database
- [x] Add image field to gear create and edit forms
- [x] Add image field data into use state and handle submit function
- [x] Test functionality
