### ISSUE TITLE
USER STORY: Add location to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#24]
As a **user** I can **add a location to my gear items** so that **I can see where each piece of gear is located**

### Acceptance Criteria:
* Acceptance Criteria 1: A location field should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the location field data should be visible on the gear card 

### Tasks:
- [x] Add location field to gear model
- [x] Migrate database
- [x] Add location field to gear create and edit forms
- [x] Add location field data into use state and handle submit function
- [x] Test functionality
