### ISSUE TITLE
USER STORY: Add serial/model numbers to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#25]
As a **user** I can **add serial/model numbers to my gear items** so that **I can have proof of ownership incase of theft**

### Acceptance Criteria:
* Acceptance Criteria 1: Serial and model text fields should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the serial and model field data should be visible on the gear card 

### Tasks:
- [x] Add serial and model text fields to gear create and edit forms
- [x] Add serial and model field data into use state, handle change and handle submit functions
- [x] Add conditionals for serial and model data into gear cards
- [x] Test functionality
