### ISSUE TITLE
USER STORY: Add year to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#26]
As a **user** I can **add a year to my gear items** so that **I can keep a record of how old my gear is**

### Acceptance Criteria:
* Acceptance Criteria 1: A year number field should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the year field data should be visible on the gear card 

### Tasks:
- [x] Add year number field to gear create and edit forms
- [x] Add year field data into use state, handle change and handle submit functions
- [x] Add conditional for year data into gear cards component
- [x] Test functionality
