### ISSUE TITLE
USER STORY: Add description to gear

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#28]
As a **user** I can **add a description to my gear items** so that **I can record any other information that I deem necessary or useful**

### Acceptance Criteria:
* Acceptance Criteria 1: A description text area field should appear in the gear create form as well as the edit gear form
* Acceptance Criteria 2: Upon submission, the description field data should be visible on the gear card 

### Tasks:
- [x] Add description text area field to gear create and edit forms
- [x] Add description field data into use state, handle change and handle submit functions
- [x] Add conditional for description data into gear card component
- [x] Test functionality
