### ISSUE TITLE
USER STORY: Mark gear for repair

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#29]
As a **user** I can **mark gear items for repair** so that **I easily keep track of which items need repairing**

### Acceptance Criteria:
* Acceptance Criteria 1: A repair select option field with yes or no options should be visible on the gear create and edit forms
* Acceptance Criteria 2: When a user selects the yes option and submits the form, a repair badge should be visible on the gear card

### Tasks:
- [x] Add repair select field with yes and no option to gear create and edit form
- [x] Add conditional to gear card to display repair badge
- [x] Style repair badge
- [x] Test functionality
