### ISSUE TITLE
USER STORY: Mark gear as insured

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#30]
As a **user** I can **mark gear items as insured** so that **I easily keep track of which items are insured**

### Acceptance Criteria:
* Acceptance Criteria 1: An insured select option field with yes or no options should be visible on the gear create and edit forms
* Acceptance Criteria 2: When a user selects the yes option and submits the form, an insured badge should be visible on the gear card

### Tasks:
- [x] Add insured field with options to gear model
- [x] Migrate database
- [x] Add insured field with yes and no option to gear create and edit form
- [x] Add conditional to gear card to display insured badge
- [x] Style insured badge
- [x] Test functionality
