### ISSUE TITLE
USER STORY: Mark gear as for sale

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#31]
As a **user** I can **mark gear items as for sale** so that **I can easily keep track of gear that I am selling**

### Acceptance Criteria:
* Acceptance Criteria 1: A sale select option field with yes or no options should be visible on the gear create and edit forms
* Acceptance Criteria 2: When a user selects the yes option and submits the form, a sale badge should be visible on the gear card

### Tasks:
- [x] Add sale select field with yes and no option to gear create and edit form
- [x] Add conditional to gear card to display sale badge
- [x] Style sale badge
- [x] Test functionality
