### ISSUE TITLE
USER STORY: Search gear page

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#33]
As a **user** I can **use a search field to search the gear on my gear page** so that **I can easily and quickly find the gear that I’m looking for**

### Acceptance Criteria:
* Acceptance Criteria 1: A search bar with a text input field should be visible to all logged in users on their gear page
* Acceptance Criteria 2: When a user adds text to the search field the gear list should be queried and all gear not matching the query should be filtered out and removed from view
* Acceptance Criteria 3: The gear list query filter method should be called after a short delay
* Acceptance Criteria 4: The user should be able to search for gear names, categories, brands, models and descriptions
* Acceptance Criteria 5: If the search bar is cleared, the gear list should return back to normal

### Tasks:
- [x] Add search bar component with query method
- [x] Import and add search bar component into gear page component
- [x] Add interval timer to query method
- [x] Pass search query as prop into gear list component
- [x] Add search method query into gear list 
- [x] Test functionality
