### ISSUE TITLE
USER STORY: Post a rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#34]
As a **user** I can **post a rig** so that **I can publicly share my rig with the site community**

### Acceptance Criteria:
* Acceptance Criteria 1: An add rig button link should be visible in the site nav menu to logged in users
* Acceptance Criteria 2: When the button is clicked the user should be directed to the rig create form component
* Acceptance Criteria 3: On submission, the user should be redirected to the rig page showing the full details of the newly created rig

### Tasks:
- [x] Add 'Add rig' button to site nav bar component with URL link to rigs/create
- [x] Add rig create form component with on change and on submit methods
- [x] Add route for rig create form into app.js
- [x] Add user redirect to rig page on successful form submission
- [x] Test functionality
