### ISSUE TITLE
USER STORY: Draft a rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#35]
As a **user** I can **draft a rig** so that **I can save it to my rigs page but not publish it publicly**

### Acceptance Criteria:
* Acceptance Criteria 1: A draft select box should be visible on the add and edit rig form components
* Acceptance Criteria 2: When selected and submitted, the rig should not be visible on the rig lists
* Acceptance Criteria 3: The rig should only be visible to the user on their my rigs page
* Acceptance Criteria 4: All drafted rigs should be marked with a draft tag icon to show their draft status

### Tasks:
- [ ] Add draft select box to create and edit rig forms
- [ ] Add draft to form use state, on change and on submit functions
- [ ] Add filtering to rigs list to remove drafted rigs except on the my rigs page
- [ ] Add conditional draft icon badge to rig cards
- [ ] Test functionality
