### ISSUE TITLE
USER STORY: Edit rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#36]
As a **user** I can **edit my rig** so that **I can change and update the rig details and contents**

### Acceptance Criteria:
* Acceptance Criteria 1: A dropdown menu with an edit button link should be visible on all rig pages for rigs owned by the user
* Acceptance Criteria 2: The dropdown menu should only be visible if the user is logged in
* Acceptance Criteria 3: Clicking the edit button should direct the user to the edit rig form page
* Acceptance Criteria 4: The form fields should be pre-populated with the data from the specific rig
* Acceptance Criteria 5: Upon successful submission, the user should be redirected back to the updated rig page

### Tasks:
- [ ] Add dropdown menu component with edit button to rig page component
- [ ] Add URL to edit button to direct the user to rigs/edit/$id
- [ ] Add conditional to only show dropdown menu if the user is logged in and owns the rig
- [ ] Add rig edit form component with on change and on submit methods
- [ ] Add route for rig edit form to app.js
- [ ] Add user redirect to rig page on successful submit
- [ ] Test functionality
