### ISSUE TITLE
USER STORY: Delete rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#37]
As a **user** I can **delete my rig** so that **I can remove it completely from the site**

### Acceptance Criteria:
* Acceptance Criteria 1: A delete icon button should be visible to a logged in user in the rig page dropdown menu
* Acceptance Criteria 2: The dropdown menu should only be visible if the user owns the rig
* Acceptance Criteria 3: Clicking the delete button should delete the rig and redirect the user back to the home page

### Tasks:
- [x] Add delete button link into rig page component
- [x] Add handle delete method
- [x] Add user redirect to home page on successful deletion
- [x] Add conditional to dropdown menu
- [x] Test functionality
