### ISSUE TITLE
USER STORY: Add gear list to rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#39]
As a **user** I can **add a gear list to my rig** so that **I can list the individual items present in my rig**

### Acceptance Criteria:
* Acceptance Criteria 1: A gear list text area field should be visible to users on the rig create form
* Acceptance Criteria 2: Upon successful submission, the rig gear list should be visible on the rig page component

### Tasks:
- [x] Add gear list text area field to rig create form
- [x] Add gear list to use state and on submit functions
- [x] Add gear list conditional to rig page component
- [x] Test functionality
