### ISSUE TITLE
USER STORY: Add description to rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#40]
As a **user** I can **add a description to my rig** so that **I can add any other details that I want to record / share with the community**

### Acceptance Criteria:
* Acceptance Criteria 1: A description field should be visible to users on the rig create form
* Acceptance Criteria 2: Upon successful submission, the rig description should be visible on the rig card and the rig page components

### Tasks:
- [x] Add description text area field to rig create form
- [x] Add description to use state and on submit functions
- [x] Add description conditional to rig card and rig page components
- [x] Test functionality
