### ISSUE TITLE
USER STORY: View user list of rigs

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#41]
As a **user** I can **view an ordered list of my rigs on my rigs page** so that **I can easily see all the rigs I have added**

### Acceptance Criteria:
* Acceptance Criteria 1: A 'Rigs' link should be visible to logged in users on the site nav bar and the footer
* Acceptance Criteria 2: Clicking the rigs link should direct the user to the rigs page
* Acceptance Criteria 3: The rigs page should contain a list of rigs created by the user, ordered from most recent to oldest

### Tasks:
- [x] Add rigs link to site nav bar and footer menus
- [x] Add rigs page component
- [x] Add route for rigs page to app.js
- [x] Add conditional to rigs page link to only display if user is logged in
- [x] Test functionality
