### ISSUE TITLE
USER STORY: View all rigs

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#42]
As a **user** I can **view an ordered list of all the published rigs** so that **I can browse through them**

### Acceptance Criteria:
* Acceptance Criteria 1: A 'Latest' link should be visible to logged in users on the site nav bar and footer
* Acceptance Criteria 2: When clicked, the user should be directed to the latest page displaying a list of rigs in descending created on order

### Tasks:
- [x] Add latest link to site nav bar and footer
- [x] Add latest page component
- [x] Add route for latest page to app.js
- [x] Test functionality
