### ISSUE TITLE
USER STORY: Change profile details

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#43]
As a **user** I can **change my profile details** so that **I can update my profile with my latest details**

### Acceptance Criteria:
* Acceptance Criteria 1: An edit profile button link should be visible to logged in users on their profile within the dropdown menu
* Acceptance Criteria 2: Clicking the edit profile button should direct the user to the edit profile form page
* Acceptance Criteria 3: The form fields in the edit profile form should be automatically pre-populated with data from the users profile
* Acceptance Criteria 4: Upon successful submission, the user should be redirected back to their profile, and the profile should display any changes made to the form fields

### Tasks:
- [x] Add edit profile button to profile dropdown
- [x] Add URL link to edit profile page to button
- [x] Add edit profile form component with on change and on submit methods
- [x] Add route for edit profile form to app.js
- [x] Add redirect to users profile on successful form submission
- [x] Test functionality
