### ISSUE TITLE
USER STORY: Add profile image

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#44]
As a **user** I can **add a profile image** so that **I can customise my profile with a personal picture**

### Acceptance Criteria:
* Acceptance Criteria 1: An edit profile button link should be visible to a logged in user in their profile dropdown menu
* Acceptance Criteria 2: Clicking the link should direct the user to the edit profile form page
* Acceptance Criteria 3: The form should contain an image field to change their profile image
* Acceptance Criteria 4: If an image is added to the form, the users profile image should change on submission
* Acceptance Criteria 5: On successful submission, the user should be redirected to their profile with their new profile image updated and displayed

### Tasks:
- [x] Add edit profile button link to profile dropdown menu
- [x] Add URL to button link for edit profile form page
- [x] Add edit profile component with on change and on submit methods
- [x] Add route for edit profile form to app.js
- [x] Add redirect to user profile on successful submission
- [x] Test functionality
