### ISSUE TITLE
USER STORY: Add contact details

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#47]
As a **user** I can **add contact details to my profile** so that **I can have my contact information visible to other users**

### Acceptance Criteria:
* Acceptance Criteria 1: An add contact details button link should be visible to users on their profile dropdown menu
* Acceptance Criteria 2: Clicking the button link should direct users to the add/edit contact details form page
* Acceptance Criteria 3: The form fields should be pre-populated with any details already added to the profile
* Acceptance Criteria 4: Form fields should include phone number, email address and social media links
* Acceptance Criteria 5: Successful submission of the form should redirect the user back to their profile with the new contact details visible

### Tasks:
- [ ] Add contact details button to profile dropdown menu
- [ ] Add contact details form URL to contact details button
- [ ] Add contact details form component with on change and on submit methods
- [ ] Add contact details form route to app.js
- [ ] Add redirect to user profile on successful form submission
- [ ] Test functionality
