### ISSUE TITLE
USER STORY: Delete contact details

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#48]
As a **user** I can **delete my contact details on my profile** so that **I can hide them from other users who view my profile**

### Acceptance Criteria:
* Acceptance Criteria 1: A delete all button should be visible to logged in users on the create / edit contact details form page
* Acceptance Criteria 2: Clicking the delete all button should delete all the users contact details and redirect them back to their profile page
* Acceptance Criteria 3: All contact details should be removed from the user profile

### Tasks:
- [ ] Add delete all button to create / edit contact details form page
- [ ] Add handle delete method to edit contact details component
- [ ] Add redirect to user profile on successful deletion 
- [ ] Test functionality
