### ISSUE TITLE
USER STORY: View profile stats

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#49]
As a **user** I can **view my profile statistics on my profile** so that **I can keep a track of how popular my profile is**

### Acceptance Criteria:
* Acceptance Criteria 1: Profile statistics should be visible to a logged in user on their own profile
* Acceptance Criteria 2: These statistics should not be visible to other users and non logged in users
* Acceptance Criteria 3: Statistics should include page views, number of rigs, number of likes, number of saves, number of fans and total value of gear

### Tasks:
- [ ] Add profile statistics component
- [ ] Add method to get statistics data
- [ ] Import and add component to profile page
- [ ] Add conditional to only display to logged in users who own the profile
- [ ] Test functionality
