### ISSUE TITLE
USER STORY: Change account username

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#5]
As a **user** I can **change my account username** so that **other users will see my updated username on my profile**

### Acceptance Criteria:
* Acceptance Criteria 1: A change username button icon should appear on a users profile dropdown menu
* Acceptance Criteria 2: Clicking the button should direct the user to the change username form page
* Acceptance Criteria 3: The form field should be pre populated with the users current username
* Acceptance Criteria 4: Changing the field and submitting the form should redirect he user back to their profile with the username display changed to the new value
* Acceptance Criteria 5: Clicking the cancel button should return the user back to their profile with no changes made

### Tasks:
- [x] Add change username button icon to profile dropdown menu
- [x] Add URL link to edit username form to edit username button
- [x] Add edit username form component with on change and on submit methods
- [x] Add route for edit username page to app.js
- [x] Test functionality
