### ISSUE TITLE
USER STORY: Rigs infinite scroll

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#51]
As a **user** I can **keep scrolling through the rigs on the site, and they are loaded automatically** so that **I don't have to click on next page to view more**

### Acceptance Criteria:
* Acceptance Criteria 1: Rigs should be displayed in lists.
* Acceptance Criteria 2: Lists should be loaded in groups of ten, and when a user scrolls down near the bottom of the list, the next section of rigs should be loaded automatically.
* Acceptance Criteria 3: A loading spinner should be displayed while the next rigs are loading.

### Tasks:
- [x] Install infinite scroll package
- [x] Import infinite scroll into rigs list
- [x] Add Infinite Scroll component with attributes to rigs list
