### ISSUE TITLE
USER STORY: Search rigs

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#54]
As a **user** I can **use a search bar to search the rigs list** so that **I can find a specific rig quickly and easily**

### Acceptance Criteria:
* Acceptance Criteria 1: A search bar with a text input field should be visible to users on all pages displaying a list of rigs
* Acceptance Criteria 2: When a user adds text to the search field the rigs list should be queried and all rigs not matching the query should be filtered out and removed from view
* Acceptance Criteria 3: The rigs list query filter method should be called after a short delay
* Acceptance Criteria 4: The user should be able to search for categories, genres, attributes, names and descriptions
* Acceptance Criteria 5: If the search bar is cleared, the rigs list should return back to normal

### Tasks:
- [x] Add search bar component with query method
- [x] Import and add search bar component into each page with a rigs list 
- [x] Add interval timer to query method
- [x] Pass search query as prop into rigs list component
- [x] Add search method query into rigs list 
- [x] Test functionality
