### ISSUE TITLE
USER STORY: Add budget to rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#55]
As a **user** I can **add a budget to my rig** so that **I can share the approximate value range of the rig**

### Acceptance Criteria:
* Acceptance Criteria 1: A budget select field with options should be visible to users on the rig create form
* Acceptance Criteria 2: Upon successful submission, the rig budget should be visible on the rig page component

### Tasks:
- [x] Add budget select field with options to rig create form
- [x] Add budget to use state and on submit functions
- [x] Add budget conditionals to rig page component
- [x] Test functionality
