### ISSUE TITLE
USER STORY: Add category to rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#56]
As a **user** I can **add a category to a rig** so that **so the rig can be sorted and searched for using the category**

### Acceptance Criteria:
* Acceptance Criteria 1: A category select field with options should be visible to users on the rig create form
* Acceptance Criteria 2: Upon successful submission, the rig category should be visible on the rig page component
### Tasks:
- [x] Add a category select field with options to rig create form
- [x] Add category to the use state and on submit functions
- [x] Add category conditional to the rig page component
- [x] Test functionality
