### ISSUE TITLE
USER STORY: Add genres to rig 

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#57]
As a **user** I can **add genres to my rig** so that **other users can see which genres this rig would be suitable for**

### Acceptance Criteria:
* Acceptance Criteria 1: Genre 1 and genre 2 select fields with options should be visible to users on the rig create form
* Acceptance Criteria 2: Upon successful submission, the rig genres should be visible on the rig page and rig card components

### Tasks:
- [x] Add genre 1 and genre 2 select fields with options to rig create form
- [x] Add genre 1 and genre 2 to use state and on submit functions
- [x] Add genre 1 and genre 2 conditionals to rig page component
- [x] Test functionality
