### ISSUE TITLE
USER STORY: View list of hottest rigs

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#58]
As a **user** I can **view a list of the hottest rigs** so that **I can see what rigs are the most popular**

### Acceptance Criteria:
* Acceptance Criteria 1: A list of the hottest rigs should be visible on the home page
* Acceptance Criteria 2: The rigs list should have a max limit of four
* Acceptance Criteria 3: The rigs should be sorted by most liked in descending order

### Tasks:
- [ ] Add rigs list component
- [ ] Add hottest rigs filter to rigs list to order from most liked descending
- [ ] Add and import rigs list component on home page
- [ ] Pass rigs list slice prop and add conditional to slice rig results 
- [ ] Test functionality
