### ISSUE TITLE
USER STORY: Change profile header image

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#59]
As a **user** I can **change my profile header image** so that **I can further customise my profile**

### Acceptance Criteria:
* Acceptance Criteria 1: A header image field should be visible on the edit profile form page to logged in users
* Acceptance Criteria 2: A user should be able to add an image to the header image field
* Acceptance Criteria 3: On successful submission, the user should be redirected to their profile and the image should be displayed as the profile header

### Tasks:
- [x] Add header image field to edit profile form component
- [x] Add header image to use state, image on change and on submit methods
- [x] Add conditional to profile page component to display the user profile image
- [x] Add default profile header image to cloudinary and copy URL
- [x] Add default profile header image URL to header image api model field
- [x] Test functionality
