### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#6]
As a **user** I can **delete my account** so that **I can remove my profile and all its content from the platform instantly**

### Acceptance Criteria:
* Acceptance Criteria 1: A delete button should be visible within a users profile dropdown menu
* Acceptance Criteria 2: Clicking the delete button should display a pop up window prompting the user to confirm their request to delete their profile
* Acceptance Criteria 3: If a user clicks the delete button on the pop up their profile should be deleted along with all their content and they should be logged out and redirected back to the home page

### Tasks:
- [ ] Add delete button icon to profile page dropdown menu
- [ ] Add delete user/profile method
- [ ] Add pop up delete confirmation to confirm user deletion
- [ ] Add redirect to method on successful completion
- [ ] Test functionality
