### ISSUE TITLE
USER STORY: Popular Profiles List

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#60]
As a **user** I can **see a list of popular profiles** so that **I can easily view their profiles and become a fan**

### Acceptance Criteria:
* Acceptance Criteria 1: A logged in user should see a list of popular profiles on any profile they visit
* Acceptance Criteria 2: Each profile in the list should feature a link to the profile as well as a username and image
* Acceptance Criteria 3: Each profile should also include a button to fan or unfan the user if the user is logged in

### Tasks:
- [ ] Create profile data context with use effect and import to index.js
- [ ] Add popular profiles component
- [ ] Add profile component and import profile to popular profiles component
- [ ] Add conditional to display fan / unfan button
- [ ] Add and import popular profiles component to profile page component
- [ ] Test functionality
