### ISSUE TITLE
USER STORY: Gear infinite scroll

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#62]
As a **user** I can **keep scrolling through my gear on the site, and they are loaded automatically** so that **I don't have to click on next page to view more**

### Acceptance Criteria:
* Acceptance Criteria 1: Gear should be displayed in a list.
* Acceptance Criteria 2: The list should be loaded in groups of ten, and when a user scrolls down near the bottom of the list, the next section of gear should be loaded automatically.
* Acceptance Criteria 3: A loading spinner should be displayed while the next gear section is loading.

### Tasks:
- [x] Install infinite scroll package
- [x] Import infinite scroll into gear list
- [x] Add Infinite Scroll component with attributes to gear list
