### ISSUE TITLE
USER STORY: View full rig details

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#63]
As a **user** I can **click on a rig to view the full rig details** so that **I can find out more information about the rig**

### Acceptance Criteria:
* Acceptance Criteria 1: A button should appear on each rig card to view the full details
* Acceptance Criteria 2: When a user clicks the button they should be redirected to the rig full details page
* Acceptance Criteria 3: The full details page should display all the details of the rig as well as full-quality images

### Tasks:
- [ ] Create full rig details template with content, logic and styling
- [ ] Add route for rig details into app.js
- [ ] Add link button with URL to rig card
