### ISSUE TITLE
USER STORY: Add social media links

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#64]
As a **user** I can **add my social media links to my profile** so that **users can connect with me on other platforms**

### Acceptance Criteria:
* Acceptance Criteria 1: Social media link fields are visible to users in the edit profile form
* Acceptance Criteria 2: The fields are optional
* Acceptance Criteria 3: The fields include instagram, facebook, twitter, linkedin and tiktok
* Acceptance Criteria 4: When the user adds their links into the fields and submits the form, the social links appear on their profile

### Tasks:
- [ ] Add twitter, facebook, instagram, linkedin and tiktok fields to profile model
- [ ] Migrate database
- [ ] Add social media text input fields to edit profile form
- [ ] Add form validation for fields
- [ ] Add conditional statements for displaying social links on user profile
- [ ] Add styling and responsiveness
- [ ] Test functionality
