### ISSUE TITLE
USER STORY: Add sound/video to rig

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#65]
As a **user** I can **add a audio clip or video recording to my rig** so that **I can share what the rig sounds like with other users**

### Acceptance Criteria:
* Acceptance Criteria 1: Audio and video fields are present in the create / edit rig forms
* Acceptance Criteria 2: Users can attach a video file or audio clip to their rig and submit the form
* Acceptance Criteria 3: The audio/video is visible on the rig details page and can be played by users

### Tasks:
- [ ] Add audio and video fields to rig model
- [ ] Migrate database
- [ ] Add video and audio input fields to rig create and edit forms
- [ ] Add form validation for fields
- [ ] Add conditional statements for displaying rig audio/video on rig details page
- [ ] Add conditional badge to rig card to display whether a rig has audio or video attached
- [ ] Add styling and responsiveness
- [ ] Test functionality
