### ISSUE TITLE
USER STORY: Become a fan of other users

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#7]
As a **user** I can **become a fan of other users** so that **I can stay easily keep updated with any new rigs that they post**

### Acceptance Criteria:
* Acceptance Criteria 1: A fan button should be visible on the profile page and popular profiles components if a user is logged in and not currently listed as a fan
* Acceptance Criteria 2: The button should not be visible on the users own profile
* Acceptance Criteria 3: Clicking the button should add the user to the users fan count, remove the fan button from the page and display the unfan button

### Tasks:
- [x] Add fan button to profile page and popular profiles components
- [x] Add fan method
- [x] Add conditional to only display to logged in users who are currently not fans
- [x] Add conditional to not display on users own profile
- [x] Add functionality to remove from view on successful fan request 
- [x] Add functionality to display unfan button when user is a fan
- [x] Test functionality
