### ISSUE TITLE
USER STORY: Remove fan

### ISSUE THREAD

**Issue by Matthew-Hurrell** [Matthew-Hurrell/gear-addict#8]
As a **user** I can **remove myself as a user fan** so that **I can remove updates of that user from my feed**

### Acceptance Criteria:
* Acceptance Criteria 1: An unfan button should be visible to logged in users when they navigate to a user profile that they are currently a fan of
* Acceptance Criteria 2: This button should also be visible on the popular profiles component
* Acceptance Criteria 3: Clicking this button should remove the user as a fan, remove the unfan button from view and display the fan button

### Tasks:
- [ ] Add unfan button to profile page and popular profiles components
- [ ] Add unfan method
- [ ] Add conditional to only show the button when a user is logged in and currently a fan
- [ ] Add conditional to hide the button on users own profile
- [ ] Add functionality to hide button on click and display fan button
- [ ] Test functionality
